### ISSUE TITLE
Expand on Chapter 02

### ISSUE THREAD

**Issue by xsawyerx** [rgs/p5-intelligible-unicode#3]
Chapter 02 should be expanded on the following points:
* Wasn't `unicode_strings` feature introduced in Perl 5.12? [This](https://metacpan.org/pod/distribution/perl/pod/perlunicode.pod#The-Unicode-Bug) says it was.
* What is the Unicode Bug? (explanation on `perlunicode` is not for humans)
* Code examples, even if it's a single line (for `use feature`, `use 5.16.0`, and `-E`).

**Comment by rgs** [comment]
7e072d9d4 should address those concerns.

**Comment by xsawyerx** [comment]
It addresses all points well. Thank you.
