### ISSUE TITLE
"Price" of utf8 pragma (Chapter 05)

### ISSUE THREAD

**Issue by xsawyerx** [rgs/p5-intelligible-unicode#4]
Would be good to explain in Chapter 05 that the `utf8` pragma carries no actual compilation or runtime price (from what I understand).

Also, I would explain another reason for not inserting pure UTF-8 characters in your code: you're either hard-coding data (which should be derived from a source) or you're making your actual code (subroutine names, for example) less accessible to others.

**Comment by rgs** [comment]
I added more notes on that chapter. Also explaining that perl is currently too buggy to handle source code in utf8 correctly. As for utf8 in data, I think that in an ideal world that would work, but I'm afraid I don't live there yet, and lots of applications claiming to support utf8 just fine actually only understand only a subset of it, or have bugs, etc.
